### ISSUE TITLE
Starting (Win 10)

### ISSUE THREAD

**Issue by apsolut** [theMosaad/sage-tailwindcss-jit#1]
Had some issues with blank page in backend without errors, so to get errors need to define `environment` ...:
` 'env' => defined('WP_ENV') ? WP_ENV : env('WP_ENV', 'development'),` inside /youthemeame/config/app.php

also another issue was inside /yourtheme/app/setup.php had to replace line 34:
` if ($manifest = asset('scripts/manifest.asset.php')->get()) {`
with:
`if ($manifest = asset('scripts/manifest.asset.php')->load()) {`

- JIT and frontend working as normal, nice for quick testings

**Comment by theMosaad** [comment]
Hey @apsolut, this sage example isn't needed as the new tailwindcss jit mode is now available in tailwindcss's core by adding `mode: 'jit'` to your tailwindcss config file.
Check https://tailwindcss.com/docs/just-in-time-mode
